version: "3.8"
services:
  notion-nav:
    image: twoice/notion-nav:latest
    container_name: notion-nav
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_CONFIG_DATABASE_ID=${NOTION_CONFIG_DATABASE_ID}
      - REVALIDATE_INTERVAL=3600
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M 