version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NOTION_TOKEN: ${NOTION_TOKEN}
        NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
        NOTION_CONFIG_DATABASE_ID: ${NOTION_CONFIG_DATABASE_ID}
    image: notion-nav:latest
    container_name: notion-nav
    restart: always
    environment:
      - NODE_ENV=production
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_CONFIG_DATABASE_ID=${NOTION_CONFIG_DATABASE_ID}
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: notion-nav-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app 