version: '3.8'
services:
  notion-nav:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_CONFIG_DATABASE_ID=${NOTION_CONFIG_DATABASE_ID}
    restart: unless-stopped 