version: '3.8'

services:
  app:
    image: twoice/notion-nav:latest
    container_name: notion-nav
    restart: always
    environment:
      - NODE_ENV=production
      - NOTION_TOKEN=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_CONFIG_DATABASE_ID=${NOTION_CONFIG_DATABASE_ID}
      - REVALIDATE_INTERVAL=300
    ports:
      - "10212:3000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3 
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 